### ISSUE TITLE
Develop fails to compile with g++

### ISSUE THREAD

**Issue by giltirn** [paboyle/Grid#232]
Unfortunately I cannot get the develop branch to compile with either g++ 7.1.0 or 9.1.0 on the CU machines. 

```
Making all in Grid
make[1]: Entering directory `/home/ckelly/qcdserver12/software/bld/grid_gpu_host/Grid'
fatal: Not a git repository (or any parent up to mount point /home/ckelly)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home/ckelly)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
make  all-am
make[2]: Entering directory `/home/ckelly/qcdserver12/software/bld/grid_gpu_host/Grid'
  CXX      algorithms/approx/MultiShiftFunction.o
In file included from /home/ckelly/qcdserver12/software/src/grid/Grid_gpu/Grid/Grid/lattice/Lattice.h:45,
                 from /home/ckelly/qcdserver12/software/src/grid/Grid_gpu/Grid/Grid/GridCore.h:58,
                 from /home/ckelly/qcdserver12/software/src/grid/Grid_gpu/Grid/Grid/algorithms/approx/MultiShiftFunction.cc:28:
/home/ckelly/qcdserver12/software/src/grid/Grid_gpu/Grid/Grid/lattice/Lattice_transfer.h: In function â€˜void Grid::blockProject(Grid::Lattice<Grid::iVector<rtype, N> >&, const Grid::Lattice<vobj>&, const std::vector<Grid::Lattice<vobj> >&)â€™:
/home/ckelly/qcdserver12/software/src/grid/Grid_gpu/Grid/Grid/lattice/Lattice_transfer.h:129:1: error: â€˜#pragmaâ€™ is not allowed here
  129 |   });
      | ^ ~
/home/ckelly/qcdserver12/software/src/grid/Grid_gpu/Grid/Grid/lattice/Lattice_transfer.h: In function â€˜void Grid::blockSum(Grid::Lattice<vobj>&, const Grid::Lattice<vobj>&)â€™:
/home/ckelly/qcdserver12/software/src/grid/Grid_gpu/Grid/Grid/lattice/Lattice_transfer.h:249:1: error: â€˜#pragmaâ€™ is not allowed here
  249 |   });
      | ^ ~
make[2]: *** [algorithms/approx/MultiShiftFunction.o] Error 1
make[2]: Leaving directory `/home/ckelly/qcdserver12/software/bld/grid_gpu_host/Grid'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/ckelly/qcdserver12/software/bld/grid_gpu_host/Grid'
make: *** [all-recursive] Error 1

```
Note the â€˜  â€™ garbage is not in the error message, it just seems to be some issue copying the error to plain text. The error seems to be related to the _Pragma commands inside the thread_for body, as if I comment out the "thread_critical" the error goes away. Unfortunately this just exposes many many more compile errors in subsequent files but it's probably best to start slow! Do you have a g++ regression on your CI server? I wonder if I am missing a flag or something.

**Comment by gfilaci** [comment]
Hi, I think the first error is related to some strange gcc behaviour (see https://github.com/paboyle/Grid/pull/225): with gcc I cannot even compile

`#define naked_for(i,num,body) for(int i=0;i<num;i++) body`
`#define thread_for(i,num,body) _Pragma("omp parallel for") naked_for(i,num,body)`
`int main () { thread_for(i,4,{_Pragma("omp critical"){}}); }`

I've been using a0b5502a944565aee4d227e58d0d551a0661caa0 as a temporary workaround, that at least should solve a couple of "thread_critical" errors.
Gianluca

**Comment by azusayamaguchi** [comment]
I managed to compile the develop and run a coupe tests ( See the file ).
The issue I am not sure is OpenMP is on or off.

**Comment by paboyle** [comment]
Will take a look.

**Comment by paboyle** [comment]
This seems related to what Gianluca mentioned in the software call.

**Comment by paboyle** [comment]
Reproduced it. Macports and OSX Mojave doesn't install GCC right, so I had to use home-brew to get gcc running .

**Comment by paboyle** [comment]
Clearly absence of a late GCC in the CI is a coverage escape.

**Comment by paboyle** [comment]
Simple example code that fails to preprocess correctly in modern G++ versions:

```
#define DO_PRAGMA(x) DO_PRAGMA_(x)
#define naked_for(i,num,...) for ( uint64_t i=0;i<num;i++) { __VA_ARGS__ } ;
#define thread_for( i, num, ... )  DO_PRAGMA(omp parallel for schedule(static)) naked_for(i,num,{__VA_ARGS__});
#define thread_critical            DO_PRAGMA(omp critical);
#define DO_PRAGMA_(x) _Pragma (#x)

thread_for(i,N,{
    int x=i;
    thread_critical {
      sum+=x;
    }
});

```

**Comment by paboyle** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91517

filed

**Comment by paboyle** [comment]
Since it appears gcc _Pragma operator is implemented in a manner (i.e. not an operator) chronically incompatible with the variadic macro direction taken in Grid it is going to prevent
capturing loop bodies in macro arguments.

i.e. whenever a pragma is used inside a loop body it will not be properly respected
by GCC.

Kokkos works around this by using extra, ugly lambda function macros inside the parallel_for 
which is ugly.

There are ~190 cases of thread_for so it is a global edit.

For now, use Clang.

**Comment by paboyle** [comment]
it is possible that configuring with

 --disable-openmp 

will help with gcc. This is how I got the GPU compile working on tesseract so there is a likelihood of success. I'm battling to get GCC working on MacOS  10.14.6 Mojave ; both Mac ports and home brew package managers have broken gcc in them.

**Comment by paboyle** [comment]
There are other problems with newer g++, even with --disable-openmp, but getting through them easily and will commit a patch that works shortly.

**Comment by paboyle** [comment]
Have committed the patch; the G++ compiles on 6/7/8/9 but only with --disable-openmp
due to the G++ preprocessor bug.

**Comment by paboyle** [comment]
Please retry and if successful close the issue

**Comment by giltirn** [comment]
It looks like it is no longer failing due to the pragma issue, but I am still not able to compile. This time it seems to be ambiguous overload errors in Init.cc:

 CXX      util/Init.o
In file included from /home/ckelly/qcdserver12/software/src/grid/Grid_gpu/Grid/Grid/lattice/Lattice.h:31,
                 from /home/ckelly/qcdserver12/software/src/grid/Grid_gpu/Grid/Grid/GridCore.h:58,
                 from /home/ckelly/qcdserver12/software/src/grid/Grid_gpu/Grid/Grid/Grid.h:41,
                 from /home/ckelly/qcdserver12/software/src/grid/Grid_gpu/Grid/Grid/util/Init.cc:49:
/home/ckelly/qcdserver12/software/src/grid/Grid_gpu/Grid/Grid/lattice/Lattice_ET.h: In instantiation of  struct Grid::BinarySub<const Grid::iScalar<Grid::iScalar<Grid::iScalar<Grid::Grid_simd<unsigned int, __vector(2) long long int> > > >&, unsigned int> :
/home/ckelly/qcdserver12/software/src/grid/Grid_gpu/Grid/Grid/lattice/Lattice_ET.h:357:1:   required by substitution of  template<class T1, class T2, typename std::enable_if<(std::is_base_of<Grid::LatticeBase, T>::value || std::is_base_of<Grid::LatticeExpressionBase, T>::value), T1>::type* <anonymous> > decltype (Grid::LatticeBinaryExpression<Grid::BinarySub<decltype (Grid::eval(0, lhs)), decltype (Grid::eval(0, rhs))>, T1, T2>(Grid::BinarySub<decltype (Grid::eval(0, lhs)), decltype (Grid::eval(0, rhs))>(), lhs, rhs)) Grid::operator-(const T1&, const T2&) [with T1 = Grid::Lattice<Grid::iScalar<Grid::iScalar<Grid::iScalar<Grid::Grid_simd<unsigned int, __vector(2) long long int> > > > >; T2 = unsigned int; typename std::enable_if<(std::is_base_of<Grid::LatticeBase, T>::value || std::is_base_of<Grid::LatticeExpressionBase, T>::value), T1>::type* <anonymous> = 0] 
/home/ckelly/qcdserver12/software/src/grid/Grid_gpu/Grid/Grid/qcd/action/gauge/Photon.h:126:72:   required from here
/home/ckelly/qcdserver12/software/src/grid/Grid_gpu/Grid/Grid/lattice/Lattice_ET.h:254:31: error: ambiguous overload for  operator-  (operand types are  const Grid::iScalar<Grid::iScalar<Grid::iScalar<Grid::Grid_simd<unsigned int, __vector(2) long long int> > > >  and  const unsigned int )
  254 | GridBinOpClass(BinarySub, lhs - rhs);
      |                           ~~~~^~~~~
/home/ckelly/qcdserver12/software/src/grid/Grid_gpu/Grid/Grid/lattice/Lattice_ET.h:247:19: note: in definition of macro  GridBinOpClass 
  247 |       -> decltype(combination) const    \
      |                   ^~~~~~~~~~~
/home/ckelly/qcdserver12/software/src/grid/Grid_gpu/Grid/Grid/lattice/Lattice_ET.h:254:31: note: candidate:  operator-(Grid::Integer {aka unsigned int}, unsigned int)  <built-in>
  254 | GridBinOpClass(BinarySub, lhs - rhs);
      |                           ~~~~^~~~~
/home/ckelly/qcdserver12/software/src/grid/Grid_gpu/Grid/Grid/lattice/Lattice_ET.h:247:19: note: in definition of macro  GridBinOpClass 
  247 |       -> decltype(combination) const    \


and many similar. My configure summary is as follows:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Summary of configuration for Grid v0.7.0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
----- GIT VERSION -------------------------------------
commit: 9b7a6d1
branch: develop
date  : 2019-08-23
----- PLATFORM ----------------------------------------
architecture (build)        : x86_64
os (build)                  : linux-gnu
architecture (target)       : x86_64
os (target)                 : linux-gnu
compiler vendor             : gnu
compiler version            : 9.1.0
----- BUILD OPTIONS -----------------------------------
SIMD                        : SSE4
Threading                   : yes
Communications type         : mpi3
Shared memory allocator     : shmopen
Shared memory mmap path     : /var/lib/hugetlbfs/global/pagesize-2MB/
Default precision           : double
Software FP16 conversion    : yes
RNG choice                  : sitmo
GMP                         : yes
LAPACK                      : no
FFTW                        : yes
LIME (ILDG support)         : yes
HDF5                        : yes
build DOXYGEN documentation : no

**Comment by paboyle** [comment]
I found 7 and 8 now work by 9 doesn't yet

**Comment by giltirn** [comment]
Confirmed able to compile with gcc7.1.
