### ISSUE TITLE
build on mac

### ISSUE THREAD

**Issue by shoji-kek** [paboyle/Grid#132]
I tried to build on my mac (OS 10.9.5) with gcc 4.9.4, and got an error  

CXX      communicator/Communicator_base.o
../../lib/communicator/Communicator_base.cc: In static member function 'static void Grid::CartesianCommunicator::ShmInitGeneric()':
../../lib/communicator/Communicator_base.cc:151:32: error: 'MAP_ANONYMOUS' was not declared in this scope
   int mmap_flag = MAP_SHARED | MAP_ANONYMOUS;
                                ^

which could be avoided by replacing MAP_ANONYMOUS by MAP_ANON in Communicator_base.cc.
In fact, my /usr/include/sys/mman.h doesn't have MAP_ANONYMOUS but does have MAP_ANON. I am not sure if this is a right thing to do.

My setting is the following.

../configure --enable-comms=none --disable-timers CXX=g++-mp-4.9 CC=gcc-mp-4.9 --enable-numa=no

$ uname -v = Darwin Kernel Version 13.4.0: Mon Jan 11 18:17:34 PST 2016; root:xnu-2422.115.15~1/RELEASE_X86_64
$ sysctl machdep.cpu.brand_string
machdep.cpu.brand_string: Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
$ gcc-mp-4.9 --version
gcc-mp-4.9 (MacPorts gcc49 4.9.4_2) 4.9.4
$ more grid.configure.summary 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Summary of configuration for Grid v0.7.0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
----- GIT VERSION -------------------------------------
commit: fddeb29d
branch: develop
date  : 2017-09-21
----- PLATFORM ----------------------------------------
architecture (build)        : x86_64
os (build)                  : darwin13.4.0
architecture (target)       : x86_64
os (target)                 : darwin13.4.0
compiler vendor             : gnu
compiler version            : 4.9.4
----- BUILD OPTIONS -----------------------------------
SIMD                        : GEN (width= 32)
Threading                   : yes
Communications type         : none
Shared memory allocator     : shmopen
Shared memory mmap path     : /var/lib/hugetlbfs/pagesize-2MB/
Default precision           : double
Software FP16 conversion    : yes
RNG choice                  : sitmo
GMP                         : no
LAPACK                      : no
FFTW                        : no
LIME (ILDG support)         : no
HDF5                        : no
build DOXYGEN documentation : no
----- BUILD FLAGS -------------------------------------
CXXFLAGS:
    -I/Users/shoji/work/Code/grid/include
    -fopenmp
    -O3
    -std=c++11
LDFLAGS:
    -L/Users/shoji/work/Code/grid/Build/lib
    -fopenmp
LIBS:
    -lz
    -lstdc++
    -lm
    -lz
-------------------------------------------------------

**Comment by paboyle** [comment]
My mac:

architecture (build)        : x86_64
os (build)                  : darwin16.7.0
architecture (target)       : x86_64
os (target)                 : darwin16.7.0

c012208:lanczos peterboyle$ uname -a
Darwin c012208.wlan.net.ed.ac.uk 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

c012208:lanczos peterboyle$ grep ANON /usr/include/sys/mman.h 
#define	MAP_ANON	0x1000	/* allocated from memory, swap space */
#define	MAP_ANONYMOUS	MAP_ANON

We could guard with an "ifdef MAP_ANONYMOUS", but you could also fix by updating your Mac.
